name: bdsim conda

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: linux conda build g4-${{ matrix.geant4-version }} ro-${{ matrix.root-version }} py-${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
#        root-version: [ "6.30.04", "6.32.04", "6.34.04", "6.36.04" ]
#        geant4-version: [ "10.7.3", "11.0.3", "11.1.3", "11.2.2", "11.3.1", "11.3.2", "11.4.1" ]
#        python-version: [ "3.10", "3.11", "3.12", "3.13"]
        root-version: [ "6.36.04" ]
        geant4-version: [ "11.4.1" ]
        python-version: [ "3.13"]

    steps:
      - uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        shell: bash -el {0}
        run: |
          conda install -y cmake pybind11 
          conda install -y -c conda-forge geant4=${{ matrix.geant4-version }} root=${{ matrix.root-version }} 

      - name: Checkout bdsim
        uses: actions/checkout@v7
        id: checkout

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v3
        id: cpu-cores

      - name: Build bdsim
        shell: bash -el {0}
        run: |
          #-DUSE_PYTHON_BINDINGS=ON 
          #-DCMAKE_PREFIX_PATH=$PYBIND_CMAKE_PATH 
          cmake -DCMAKE_CXX_STANDARD=17 \
          -DCMAKE_INSTALL_PREFIX=/tmp/bdsim-install \
          $GITHUB_WORKSPACE 
          make -j${{ steps.cpu-cores.outputs.count }}
          make install 

      - name: Test bdsim
        shell: bash
        run: |
          # Set up bdsim 
          source /tmp/bdsim-install/bin/bdsim.sh

          # run tests
          cd /tmp/bdsim-build
          ctest -j1