name: cvmfs bdsim

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    
    strategy:
      fail-fast: false
      matrix:
        container: [almalinux:8, almalinux:9]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install deps
      run: |
        dnf install -y epel-release 
        dnf install -y lsb_release
	

    - name: Setup CVMFS
      uses: cvmfs-contrib/github-action-cvmfs@v4

    - name: Test CernVM-FS
      run: ls /cvmfs/sft.cern.ch/

