name: cvmfs bdsim

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup CVMFS
      uses: uses: cvmfs-contrib/github-action-cvmfs@v4

    - name: Run container
      run:
        docker pull almalinux:9
        docker run -v /cvmfs:/cvmfs:shared -ti almalinux:9

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Test CernVM-FS
      run: ls /cvmfs/sft.cern.ch/

