name: cvmfs bdsim

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: [almalinux:8, almalinux:9]
        lcg: [LCG100]

    steps:
    - name: Setup CVMFS
      uses: cvmfs-contrib/github-action-cvmfs@v4

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Test CernVM-FS
      run: ls /cvmfs/sft.cern.ch/

    - name: Run container
      run: |
        docker pull ${{ matrix.container }}
        docker run -v /cvmfs:/cvmfs:shared -v $PWD:/repo ${{ matrix.container }} /repo/.github/bin/cvmfs_build.sh x86_64 el9 gcc15 108 11.3.2 

